name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        env:
          FLASK_CONFIG: production
          FLASK_APP: app.py
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          VITE_API_URL: ${{ secrets.EC2_HOST }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          envs: FLASK_CONFIG, FLASK_APP, DATABASE_URL, JWT_SECRET_KEY, VITE_API_URL
          script: |
            echo "Starting deployment..."

            # Create app directory if it doesn't exist
            mkdir -p ~/app
            cd ~/app

            # Clone repo if it's the first time, otherwise pull
            if [ ! -d ".git" ]; then
              git clone https://github.com/npatel98/DTSA5714-Web-Application.git .
            else
              git pull origin main
            fi

            # Set up Python virtual environment if it doesn't exist
            if [ ! -d "venv" ]; then
              python3 -m venv venv
            fi

            # Activate virtual environment and update dependencies
            source venv/bin/activate
            cd backend
            pip install -r requirements.txt

            # Run database migrations
            echo "Running database migrations..."
            if ! flask db upgrade; then
                echo "ERROR: Database migration failed"
                exit 1
            fi
            echo "Database migrations completed successfully"

                        # Configure nginx
            echo "Configuring nginx..."
            sudo tee /etc/nginx/sites-available/expense-tracker << EOF
            server {
                listen 80 default_server;
                root /home/ubuntu/app/frontend/dist;
                index index.html;

                # Frontend
                location / {
                    try_files \$uri \$uri/ /index.html;
                }

                # Backend API
                location /api {
                    rewrite ^/api/(.*) /\$1 break;
                    proxy_pass http://127.0.0.1:5000;
                    proxy_set_header Host \$host;
                    proxy_set_header X-Real-IP \$remote_addr;
                    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                    proxy_set_header X-Forwarded-Proto \$scheme;
                }
            }
            EOF

            # Remove default nginx site and enable our site
            sudo rm -f /etc/nginx/sites-enabled/default
            sudo ln -sf /etc/nginx/sites-available/expense-tracker /etc/nginx/sites-enabled/

            # Test and restart nginx
            echo "Testing nginx configuration..."
            if ! sudo nginx -t; then
                echo "ERROR: nginx configuration test failed"
                exit 1
            fi
            sudo systemctl restart nginx

            # Enable nginx site
            sudo ln -sf /etc/nginx/sites-available/expense-tracker /etc/nginx/sites-enabled/
            sudo nginx -t && sudo systemctl restart nginx

            # Create systemd service file
            echo "Creating systemd service file..."
            sudo tee /etc/systemd/system/expense-tracker.service << EOF
            [Unit]
            Description=Expense Tracker Flask Application
            After=network.target

            [Service]
            User=ubuntu
            WorkingDirectory=/home/ubuntu/app/backend
            Environment="PATH=/home/ubuntu/app/backend/venv/bin"
            Environment="FLASK_APP=${FLASK_APP}"
            Environment="FLASK_CONFIG=${FLASK_CONFIG}"
            Environment="DATABASE_URL=${DATABASE_URL}"
            Environment="JWT_SECRET_KEY=${JWT_SECRET_KEY}"
            ExecStart=/home/ubuntu/app/backend/venv/bin/gunicorn -w 4 -b 127.0.0.1:5000 app:app --log-level debug
            StandardOutput=append:/var/log/expense-tracker.log
            StandardError=append:/var/log/expense-tracker.error.log
            Restart=always

            [Install]
            WantedBy=multi-user.target
            EOF

            # Create log files and set permissions
            sudo touch /var/log/expense-tracker.log /var/log/expense-tracker.error.log
            sudo chown ubuntu:ubuntu /var/log/expense-tracker.log /var/log/expense-tracker.error.log

            # Reload systemd and restart service
            sudo systemctl daemon-reload
            sudo systemctl enable expense-tracker
            sudo systemctl restart expense-tracker

            # Build and deploy frontend
            echo "Building and deploying frontend..."
            cd ../frontend
            npm ci
            npm run build

            # Set proper permissions for nginx to read frontend files
            sudo chown -R ubuntu:ubuntu dist
            sudo chmod -R 755 dist

            # Verify nginx configuration and restart
            sudo nginx -t && sudo systemctl restart nginx

            echo "Deployment completed successfully"
